-   id: argparse_to_md
    name: Argparse to Markdown
    description: Generates and updates Markdown documentation snippets from argparse parsers.
    entry: argparse_to_md
    pass_filenames: false
    language: python
    types_or: [markdown, python]
    args: [--input=README.md]
