name: CI
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the package and the dependencies
        run: pip install -e ".[dev]"
      - name: Run tests with pytest
        run: pytest

  build_wheels:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - run: python3 -m pip install --upgrade setuptools build
    - run: |
        python3 -m build
        find dist
    - name: Upload wheels as job artifacts
      if: github.event_name == 'push' && github.ref_type == 'tag'
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist
    - name: Sanity-check the resulting wheel
      run: |
        python3 -m venv venv
        . venv/bin/activate
        pip install dist/*.whl
        argparse_to_md --version

  upload_wheels:
    if: github.event_name == 'push' && github.ref_type == 'tag'
    permissions:
      id-token: write
    needs: build_wheels
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Download wheels from artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
